metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      
metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: [ "unix:///var/run/docker.sock" ]
    period: 10s
    enabled: true
  - module: prometheus
    period: 10s
    metricsets: ["collector"]
    hosts: [ "webmvc", "webspa", "webshoppingagg", "mobileshoppingagg", "ordering-api", "basket-api", "catalog-api", "identity-api", "payment-api", "ordering-signalrhub", "ordering-backgroundtasks" ]
    metrics_path: /metrics

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: [ "elasticsearch:9200" ]
setup:
  kibana:
    host: "kibana:5601"
  ilm.overwrite: true
