receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
#  prometheus:
#    endpoint: "0.0.0.0:8889"
#    namespace: promexample
#    const_labels:
#      label1: value1
  logging:

#  zipkin:
#    endpoint: "http://zipkin:9411/api/v2/spans"
#    format: proto
#
#  jaeger:
#    endpoint: jaeger:14250
#    insecure: true

#  elastic:
#    apm_server_url: 'http://apm-server:8200'
#    insecure: true

  otlp:
    endpoint: 'tempo:4317'
    insecure: true

processors:
  batch:

extensions:
  health_check:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
