server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: push1
  pipeline_stages:
    - json:
        expressions:
          TraceId:
        source: output
  loki_push_api:
    server:
      http_listen_port: 3500
      grpc_listen_port: 3600
